import type { Product } from '@/lib/types';

export const sampleProducts: Product[] = [
  {
    id: '1',
    slug: 'strawberry-glazed',
    name_tr: 'Çilekli Glazürlü',
    name_en: 'Strawberry Glazed',
    description_tr: 'Taze çilek glazürü ile kaplı, hafif ve lezzetli donut. Premium çilek özü ve özel glazür karışımımızla hazırlanmıştır.',
    description_en: 'Light and delicious donut covered with fresh strawberry glaze. Made with premium strawberry extract and our special glaze recipe.',
    price: 45,
    image_url: '/donut 4.png',
    category: 'glazed',
    stock: 25,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'chocolate-dream',
    name_tr: 'Çikolata Rüyası',
    name_en: 'Chocolate Dream',
    description_tr: 'İçi çikolata kreması dolu, üzeri kakao tozlu özel donut. Belçika çikolatasıyla hazırlanır.',
    description_en: 'Special donut filled with chocolate cream and dusted with cocoa powder. Made with Belgian chocolate.',
    price: 50,
    image_url: '/donut 5.png',
    category: 'filled',
    stock: 20,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'classic-sugar',
    name_tr: 'Klasik Şekerli',
    name_en: 'Classic Sugar',
    description_tr: 'Geleneksel ince şeker tozuyla kaplanmış klasik donut. Sade ve zamanın ötesinde lezzet.',
    description_en: 'Traditional donut coated with fine sugar powder. Simple and timeless flavor.',
    price: 40,
    image_url: '/donut 6.png',
    category: 'glazed',
    stock: 30,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    slug: 'caramel-delight',
    name_tr: 'Karamelli Şahane',
    name_en: 'Caramel Delight',
    description_tr: 'Tuzlu karamel sosuyla süslenmiş özel donut. Her lokmada karamel patlaması.',
    description_en: 'Special donut topped with salted caramel sauce. A burst of caramel in every bite.',
    price: 55,
    image_url: '/donut 6 (2).png',
    category: 'specialty',
    stock: 15,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    slug: 'rainbow-sprinkles',
    name_tr: 'Renkli Boncuklu',
    name_en: 'Rainbow Sprinkles',
    description_tr: 'Renkli şeker boncuklarıyla süslenmiş neşeli donut. Çocukların ve gençlerin favorisi.',
    description_en: 'Cheerful donut decorated with rainbow sprinkles. A favorite among kids and teens.',
    price: 45,
    image_url: '/9877db2dcff20bf4feec3349824f74e3.png',
    category: 'glazed',
    stock: 28,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    slug: 'vanilla-cream',
    name_tr: 'Vanilyalı Kremalı',
    name_en: 'Vanilla Cream',
    description_tr: 'İçi vanilyalı krema dolu, üzeri pudra şekeri. Madagaskar vanilyası kullanılır.',
    description_en: 'Filled with vanilla cream and dusted with powdered sugar. Made with Madagascar vanilla.',
    price: 48,
    image_url: '/a0f87c462026bee95d2ccf126b9bc60a.png',
    category: 'filled',
    stock: 22,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    slug: 'maple-bacon',
    name_tr: 'Akçaağaç & Bacon',
    name_en: 'Maple Bacon',
    description_tr: 'Akçaağaç şurubu ve çıtır bacon parçalarıyla kaplı. Tatlı ve tuzlu mükemmel uyum.',
    description_en: 'Topped with maple syrup and crispy bacon bits. The perfect sweet and savory combo.',
    price: 60,
    image_url: '/donut (3).png',
    category: 'specialty',
    stock: 12,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    slug: 'pumpkin-spice',
    name_tr: 'Balkabağı Baharat',
    name_en: 'Pumpkin Spice',
    description_tr: 'Mevsimsel balkabağı baharatı ile hazırlanan sonbahar lezzeti.',
    description_en: 'Seasonal autumn flavor made with pumpkin spice blend.',
    price: 52,
    image_url: '/e7477fc5ceac0d47e8eade2ff3d7354c.png',
    category: 'seasonal',
    stock: 18,
    featured: false,
    created_at: new Date().toISOString(),
  },
  // Beverages
  {
    id: '9',
    slug: 'berry-bliss-smoothie',
    name_tr: 'Berry Bliss Smoothie',
    name_en: 'Berry Bliss Smoothie',
    description_tr: 'Taze çilek, yaban mersini ve ahududu ile hazırlanan ferahlatıcı smoothie. Doğal meyvelerden.',
    description_en: 'Refreshing smoothie made with fresh strawberries, blueberries and raspberries. From natural fruits.',
    price: 65,
    image_url: '/beverage 1.png',
    category: 'beverage',
    stock: 50,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    slug: 'chocolate-milkshake',
    name_tr: 'Çikolatalı Milkshake',
    name_en: 'Chocolate Milkshake',
    description_tr: 'Kremsi Belçika çikolatalı milkshake. Üzerinde krem şanti ve çikolata sosu.',
    description_en: 'Creamy Belgian chocolate milkshake. Topped with whipped cream and chocolate sauce.',
    price: 70,
    image_url: '/beverage 2.png',
    category: 'beverage',
    stock: 40,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    slug: 'caramel-frappe',
    name_tr: 'Karamelli Frappe',
    name_en: 'Caramel Frappe',
    description_tr: 'Buzlu karamelli kahve, krem şanti ile taçlandırılmış. Tatlı sevenler için.',
    description_en: 'Iced caramel coffee topped with whipped cream. For sweet lovers.',
    price: 68,
    image_url: '/beverage 3.png',
    category: 'beverage',
    stock: 35,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    slug: 'strawberry-lemonade',
    name_tr: 'Çilekli Limonata',
    name_en: 'Strawberry Lemonade',
    description_tr: 'Taze çilek ve limon ile hazırlanan serinletici içecek. Yaz favorisi.',
    description_en: 'Refreshing drink made with fresh strawberries and lemon. Summer favorite.',
    price: 55,
    image_url: '/beverage 4.png',
    category: 'beverage',
    stock: 60,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '13',
    slug: 'vanilla-iced-latte',
    name_tr: 'Vanilyalı Buzlu Latte',
    name_en: 'Vanilla Iced Latte',
    description_tr: 'Soğuk espresso ve vanilya şurubu ile hazırlanan kremsi latte.',
    description_en: 'Creamy latte made with cold espresso and vanilla syrup.',
    price: 62,
    image_url: '/beverage 5.png',
    category: 'beverage',
    stock: 45,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '14',
    slug: 'mango-passion-smoothie',
    name_tr: 'Mango Passion Smoothie',
    name_en: 'Mango Passion Smoothie',
    description_tr: 'Tropikal mango ve çarkıfelek meyvesi ile hazırlanan egzotik smoothie.',
    description_en: 'Exotic smoothie made with tropical mango and passion fruit.',
    price: 68,
    image_url: '/beverage 6.png',
    category: 'beverage',
    stock: 38,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '15',
    slug: 'iced-mocha',
    name_tr: 'Buzlu Mocha',
    name_en: 'Iced Mocha',
    description_tr: 'Espresso, çikolata ve soğuk süt birleşimi. Kahve ve çikolata severler için.',
    description_en: 'Combination of espresso, chocolate and cold milk. For coffee and chocolate lovers.',
    price: 72,
    image_url: '/beverage 7.png',
    category: 'beverage',
    stock: 42,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '16',
    slug: 'pink-cloud-shake',
    name_tr: 'Pembe Bulut Shake',
    name_en: 'Pink Cloud Shake',
    description_tr: 'Çilekli ve frambuazlı özel pembe milkshake. Instagram favorisi!',
    description_en: 'Special pink milkshake with strawberry and raspberry. Instagram favorite!',
    price: 75,
    image_url: '/beverage 18.png',
    category: 'beverage',
    stock: 30,
    featured: true,
    created_at: new Date().toISOString(),
  },
];
